# Name of nodes to start
# here we have a single node
CELERYD_NODES="w1"
# or we could have three nodes:
#CELERYD_NODES="w1 w2 w3"

# Absolute or relative path to the 'celery' command:
CELERY_BIN="{{ project_venv }}/bin/celery"

# App instance to use
# comment out this line if you don't use an app
CELERY_APP="fix_the_news"
# or fully qualified:
#CELERY_APP="proj.tasks:app"

# How to call manage.py
CELERYD_MULTI="multi"

# Extra command-line arguments to the worker
CELERYD_OPTS="--time-limit=300 --concurrency=8"

# - %n will be replaced with the first part of the nodename.
# - %I will be replaced with the current child process index
#   and is important when using the prefork pool to avoid race conditions.
CELERYD_PID_FILE="/var/run/celery/%n.pid"
CELERYD_LOG_FILE="/var/log/celery/%n%I.log"
CELERYD_LOG_LEVEL="INFO"

# you may wish to add these options for Celery Beat
#CELERYBEAT_PID_FILE="/var/run/celery/beat.pid"
#CELERYBEAT_LOG_FILE="/var/log/celery/beat.log"

# Python interpreter from environment.
ENV_PYTHON="{{ project_venv }}/bin/python3"

AWS_ACCESS_KEY_ID="{{ AWS_ACCESS_KEY_ID }}"
AWS_SECRET_ACCESS_KEY="{{ AWS_SECRET_ACCESS_KEY }}"
AWS_S3_REGION_NAME="{{ AWS_S3_REGION_NAME }}"
AWS_MEDIA_BUCKET_NAME="{{ AWS_MEDIA_BUCKET_NAME }}"
SECRET_KEY="{{ SECRET_KEY }}"
DEBUG="{{ DEBUG }}"
DJANGO_SETTINGS_MODULE="{{ DJANGO_SETTINGS_MODULE }}"
DATABASE_NAME="{{ DATABASE_NAME }}"
DATABASE_USER="{{ DATABASE_USER }}"
DATABASE_PASSWORD="{{ DATABASE_PASSWORD }}"
DATABASE_HOST="{{ DATABASE_HOST }}"
DATABASE_PORT="{{ DATABASE_PORT }}"
DJANGO_HOST="{{ DJANGO_HOST }}"
DJANGO_SETTINGS_MODULE="{{ DJANGO_SETTINGS_MODULE }}"
CELERY_BROKER_URL="{{ CELERY_BROKER_URL }}"
WEB_APP_HOST="{{ WEB_APP_HOST }}"
SENTRY_KEY="{{ SENTRY_KEY }}"
SENTRY_ORGANISATION="{{ SENTRY_ORGANISATION }}"
SENTRY_PROJECT="{{ SENTRY_PROJECT }}"
