---
- name: copy build files to web root
  become: yes
  become_user: "{{ project_user }}"
  synchronize:
    src: "{{ project_path }}/build/"
    dest: "{{ webroot }}"
    rsync_opts:
      - "-av"
  delegate_to: "{{ inventory_hostname }}"
