---
- name: install gpg key for nodejs
  become: yes
  become_method: sudo
  apt_key:
    url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
    state: present

- name: install the nodejs repos
  become: yes
  become_method: sudo
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_{{ node_version }}.x {{ distribution_release }} main"
    state: present
    update_cache: yes

- name: install the nodejs
  become: yes
  become_method: sudo
  apt:
    name: nodejs
    state: present
