---
- name: create /etc/letsencrypt
  become: yes
  become_method: sudo
  file:
    group: root
    owner: root
    path: /etc/letsencrypt/{{ item }}/fixthenews.com
    state: directory
    mode: "0755"
  loop:
    - archive
    - live

- name: sync /etc/letsencrypt
  become: yes
  become_method: sudo
  synchronize:
    src: /etc/letsencrypt/archive/fixthenews.com/{{ item }}
    dest: /etc/letsencrypt/archive/fixthenews.com/{{ item }}
  loop:
    - fullchain1.pem
    - privkey1.pem

# TODO - whenever we update certs the archive name bumps up 1
# for example fullchain1.pem becomes fullchain2.pem. This needs
# to be fixed
- name: create symbolic links
  become: yes
  become_method: sudo
  file:
    src: /etc/letsencrypt/archive/fixthenews.com/{{ item.archive_name }}
    dest: /etc/letsencrypt/live/fixthenews.com/{{ item.live_name }}
    owner: root
    group: root
    state: link
    mode: "0777"
  loop:
    - { archive_name: fullchain1.pem, live_name: fullchain.pem }
    - { archive_name: privkey1.pem, live_name:  privkey.pem }
