---
- name: create /etc/letsencrypt
  become: yes
  become_method: sudo
  file:
    group: root
    owner: root
    path: /etc/letsencrypt/live/fixthenews.com
    state: directory
    mode: "0755"

- name: copy SSL files
  copy:
    src: /etc/letsencrypt/live/fixthenews.com/{{ item }}
    dest: /etc/letsencrypt/live/fixthenews.com/{{ item }}
    owner: root
    group: root
    mode: "0777"
  loop:
    - fullchain.pem
    - privkey.pem
