---
- name: add trusted rabbit key
  become: yes
  become_method: sudo
  apt_key:
    url: "https://www.rabbitmq.com/rabbitmq-release-signing-key.asc"
    state: present

- name: add rabbit repo
  become: yes
  become_method: sudo
  apt_repository:
    repo: "deb http://www.rabbitmq.com/debian/ testing main"
    state: present
    update_cache: yes
    filename: rabbitmq.list

- name: install rabbitmq
  become: yes
  become_method: sudo
  apt:
    name: rabbitmq-server
    state: present
    update_cache: yes

- name: enable rabbitmq plugins
  become: yes
  become_method: sudo
  rabbitmq_plugin:
    names: rabbitmq_management
    state: enabled
  notify:
    - restart rabbitmq

- name: add rabbitmq users admin
  become: yes
  become_method: sudo
  rabbitmq_user:
    user: "{{ rabbit_admin_user }}"
    password: "{{ rabbit_admin_password }}"
    vhost: /
    tags: administrator
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present
