---
- name: template a file to /etc/nginx/nginx.conf
  become: yes
  become_method: sudo
  template:
    src: roles/nginx/templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: "0644"

- name: template a file to /etc/nginx/sites-available/{{ nginx_site_file }}
  become: yes
  become_method: sudo
  template:
    src: roles/nginx/templates/{{ nginx_site_file }}.j2
    dest: /etc/nginx/sites-available/{{ nginx_site_file }}
    owner: "{{ project_user }}"
    group: "{{ project_user }}"
    mode: "0644"

- name: create symbolic link to sites-enabled
  become: yes
  become_method: sudo
  file:
    src: /etc/nginx/sites-available/{{ nginx_site_file }}
    dest: /etc/nginx/sites-enabled/{{ nginx_site_file }}
    owner: "{{ project_user }}"
    group: "{{ project_user }}"
    state: link
