---
- name: copy anisble secrets
  synchronize:
    src: password.txt
    dest: "{{ project_path }}/ansible/password.txt"

- name: copy terraform secrets
  synchronize:
    src: ../terraform/{{ item }}/terraform.tfvars
    dest: "{{ project_path }}/terraform/{{ item }}/terraform.tfvars"
  loop:
    - "staging"
