- name: create project directory
  become: yes
  become_method: sudo
  file:
    group: "{{ devops_user }}"
    owner: "{{ devops_user }}"
    path: "{{ project_path }}"
    state: directory
    mode: "0770"

- name: download project code
  become: yes
  become_user: "{{ devops_user }}"
  git:
    repo: "{{ project_repo }}"
    dest: "{{ project_path }}"
