---
- name: download terraform {{ terraform_version }}
  become: yes
  become_method: sudo
  get_url:
    url: "{{ terraform_download_url }}"
    dest: "{{ downloads_directory }}"
    mode: "0644"

- name: unzip terraform {{ terraform_version }} to /usr/local/bin
  become: yes
  become_method: sudo
  unarchive:
    src: "{{ downloads_directory }}/{{ terraform_filename }}"
    dest: /usr/local/bin
    remote_src: yes
